local M = {}

local nvim_treesitter_configs = require('nvim-treesitter.configs')

function M.setup()
  vim.g.skip_ts_context_commentstring_module = true
  require('ts_context_commentstring').setup({})
  nvim_treesitter_configs.setup({
    -- ref: https://github.com/nvim-treesitter/nvim-treesitter
    ensure_installed = {
      'angular',
      'bash',
      'c',
      'cpp',
      'cmake',
      'css',
      'csv',
      'dockerfile',
      'editorconfig',
      'fish',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'go',
      'goctl',
      'gomod',
      'gosum',
      'groovy',
      'haskell',
      'haskell_persistent',
      'hcl',
      'helm',
      'hjson',
      'html',
      'htmldjango',
      'hyprlang',
      'java',
      'javadoc',
      'javascript',
      'jq',
      'jsdoc',
      'json',
      'jsonc',
      'jsonnet',
      'just',
      'kcl',
      'kconfig',
      'latex',
      'llvm',
      'lua',
      'luadoc',
      'luap',
      'markdown',
      'markdown_inline',
      'meson',
      'nginx',
      'nix',
      'nu',
      'properties',
      'proto',
      'python',
      'r',
      'regex',
      'rego',
      'requirements',
      'ruby',
      'rust',
      'scss',
      'sql',
      'ssh_config',
      'terraform',
      'tmux',
      'toml',
      'tsx',
      'typescript',
      'typespec',
      'vim',
      'vimdoc',
      'vue',
      'query',
      'xml',
      'xresources',
      'yaml',
    },
    -- ensure_installed = 'all',
    -- ignore_install = { 'swift', 'phpdoc', 'beancount' },
    autopairs = { enable = true },
    highlight = { enable = true },
    -- indent = { enable = true },
    rainbow = { enable = true, extended_mode = true },
    textobjects = {
      select = {
        enable = true,
        lookahead = true,
      },
    },
  })
end

return M
