local settings = {
  header = {
    type = 'text',
    oldfiles_directory = false,
    align = 'center',
    fold_section = false,
    title = 'Header',
    margin = 5,
    content = {
      ' ███╗   ██╗ ██╗   ██╗ ██╗ ███╗   ███╗',
      ' ████╗  ██║ ██║   ██║ ██║ ████╗ ████║',
      ' ██╔██╗ ██║ ██║   ██║ ██║ ██╔████╔██║',
      ' ██║╚██╗██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║',
      ' ██║ ╚████║  ╚████╔╝  ██║ ██║ ╚═╝ ██║',
      ' ╚═╝  ╚═══╝   ╚═══╝   ╚═╝ ╚═╝     ╚═╝',
    },
    highlight = 'Statement',
    default_color = '',
    oldfiles_amount = 0,
  },
  -- name which will be displayed and command
  body = {
    type = 'mapping',
    oldfiles_directory = false,
    align = 'center',
    fold_section = false,
    title = 'Basic Commands',
    margin = 10,
    content = {
      { ' Recent Files', 'Telescope oldfiles hidden=true prompt_prefix=🔍', 'go' },
      { ' Recent Projects', 'Telescope projects hidden=true prompt_prefix=🔍', 'gp' },
      { ' Find Projects', 'Telescope repo list search_dirs=~/Workspace hidden=true prompt_prefix=🔍', 'gP' },
      { ' Find File', 'Telescope find_files hidden=true prompt_prefix=🔍', 'gO' },
      { ' File Browser', 'Telescope file_browser hidden=true prompt_prefix=🔍', '<leader>fe' },
      { ' New File', "lua require'startup'.new_file()", '<leader>nf' },
    },
    highlight = 'String',
    default_color = '',
    oldfiles_amount = 0,
  },
  footer = {
    type = 'text',
    oldfiles_directory = false,
    align = 'center',
    fold_section = false,
    title = 'Footer',
    margin = 5,
    content = { 'startup.nvim' },
    highlight = 'Number',
    default_color = '',
    oldfiles_amount = 0,
  },
  options = {
    mapping_keys = true,
    cursor_column = 0.5,
    empty_lines_between_mappings = true,
    disable_statuslines = true,
    paddings = { 1, 3, 3, 0 },
  },
  mappings = {
    execute_command = '<CR>',
    open_file = 'o',
    open_file_split = '<c-o>',
    open_section = '<TAB>',
    open_help = '?',
  },
  colors = {
    background = '#1f2227',
    folded_section = '#56b6c2',
  },
  parts = { 'header', 'body', 'footer' },
}

return settings
